schema: lexadb
name: "ぶろみ, Bromi"
author: "Stefano Coretta"
languages:
  bro: "Bromi"
  meta:
    eng: "English"
    jpn: "Japanese"
scripts:
  bro:
    hira: "Bromi Hiragana"
    translit: "Bromi transliteration"
  eng: "eng"
  jpn: "jpn"
